<<<<<<< HEAD

next_addressbook_contact_details:
    path:     /contact/{id}
    defaults: { _controller: NextJobsBundle:Contact:details }
    requirements: 
        id: "[1-9][0-9]*"

next_addressbook_contact_lister:
    path:     /
    defaults: { _controller: NextAddressBookBundle:Contact:lister }

next_addressbook_contact_ajouter:
    path:     /contact/ajouter
    defaults: { _controller: NextAddressBookBundle:Contact:ajouter }

next_addressbook_contact_modifier:
    path:     /contact/modifier/{idcontact}
    defaults: { _controller: NextAddressBookBundle:Contact:modifier }

next_addressbook_contact_supprimer:
    path:     /contact/supprimer/{idcontact}
    defaults: { _controller: NextAddressBookBundle:Contact:supprimer }

next_addressbook_contact_lister_par_societe:
    path:     /contact/societe/{idsociete}
    defaults: { _controller: NextAddressBookBundle:Contact:listerParSociete }

next_addressbook_contact_lister_par_groupe:
    path:     /contact/groupe/{nomgroupe}
    defaults: { _controller: NextAddressBookBundle:Contact:listerParGroupe }
=======
next_address_book_lister:
    path:     /societe/lister
    defaults: { _controller: NextAddressBookBundle:Societe:lister }

next_address_book_ajouter:
    path:     /societe/ajouter
    defaults: { _controller: NextAddressBookBundle:Societe:ajouter }

next_address_book_modifier:
    path:     /societe/modifier/{id}
    defaults: { _controller: NextAddressBookBundle:Societe:modifier }
    requirements:
        id: "[1-9][0-9]*"
>>>>>>> 9dea59b25ab7a927e726bdae7d72086bb74668e6
