parameters:
#    next_address_book.example.class: Next\AddressBookBundle\Example


#    next_address_book.example:
#        class: %next_address_book.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    next_addressbook.contact:
        class: Next\AddressBookBundle\Entity\Contact
    next_addressbook.contact.form:
        class: Next\AddressBookBundle\Form\ContactForm
        tags:
            - { name: form.type, alias: ContactForm }
    next_addressbook.societe:
        class: Next\AddressBookBundle\Entity\Societe
    next_addressbook.societe.form:
        class: Next\AddressBookBundle\Form\SocieteForm
        tags:
            - { name: form.type, alias: SocieteForm }
    twig.extension.text:
        class: Twig_Extensions_Extension_Text 
        tags:
            - { name: twig.extension }
