parameters:
#    next_address_book.example.class: Next\AddressBookBundle\Example

services:
#    next_address_book.example:
#        class: %next_address_book.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
