Next\AddressBookBundle\Entity\Contact:
    properties:
        nom:
            - NotBlank:
                message: "Le nom est obligatoire"
            - Length:
                max: 45 
                maxMessage: "Le nom ne doit pas dépasser 45 caractères"
        prenom:
            - NotBlank: 
                message: "Le prenom est obligatoire"
Next\AddressBookBundle\Entity\Societe:
    properties:
        nom:
            - NotBlank:
                message: "Le nom est obligatoire"
            - Length:
                max: 45 
                maxMessage: "Le nom ne doit pas dépasser 45 caractères"
Next\AddressBookBundle\Entity\Groupe:
    properties:
        nomgroupe:
            - NotBlank:
                message: "Le nom est obligatoire"
            - Length:
                max: 30 
                maxMessage: "Le nom ne doit pas dépasser 30 caractères"              

